AWSTemplateFormatVersion: "2010-09-09"
Description: API docs infrastructure

Parameters:
  pEnvironment:
    Type: String
    AllowedValues:
         - development
         - testing
         - staging
         - production
    Description: The environment this belongs to
  pDocumentationBucket:
    Type: String
    Description: The bucket name for the docs
  pBucketPath:
    Type: String
    Description: Optional path that the documentation is stored under
  pCleanBranch:
    Type: String
    Description: A clean version of the branch, used for resource naming
  pHostedZone:
    Type: String
    Description: The hosted zone the docs are accessed under
  pSubDomain:
    Type: String
    Description: The subdomain the docs are accessed on
  pSslCertificate:
    Type: String
    Description: The arn of the SSL certificate to be used 

Conditions:
  IsDev: !Equals
    - !Ref pEnvironment
    - development

Resources:
  
  ApiDocsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${pDocumentationBucket}
      LifecycleConfiguration:
        Rules:
          - Id: delete incomplete uploads
            AbortIncompleteMultipartUpload:
               DaysAfterInitiation: 1
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        RestrictPublicBuckets: TRUE
        IgnorePublicAcls: TRUE
      Tags:
        - Key: Name
          Value: !Ref pDocumentationBucket

  ApiDocsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ApiDocsBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Join [ '', ['arn:aws:s3:::', !Ref ApiDocsBucket ,'/*' ]]
            Principal: 
              AWS: !Join [ '', [ 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ', !Ref ApiDocsCloudFrontOai ]]

  ApiDocsDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub "${pSubDomain}.${pHostedZone}"
      Comment: !Sub API docs domain for the ${pEnvironment} environment
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiDocsCloudFrontDistro.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneName: !Sub "${pHostedZone}."

  ApiDocsCloudFrontDistro:
    Type: AWS::CloudFront::Distribution
    DependsOn: ApiDocsBucket
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub "${pSubDomain}.${pHostedZone}"
        Comment: !Sub API Docs portal ${pEnvironment}
        DefaultCacheBehavior:
          AllowedMethods: 
            - GET
            - HEAD
          CachedMethods: 
            - GET
            - HEAD
          CachePolicyId: !Ref ApiDocsCachePolicy 
          Compress: true
          TargetOriginId: api-docs-s3
          ViewerProtocolPolicy: redirect-to-https 
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: false
        Origins:
          - DomainName: !Sub ${pDocumentationBucket}.s3.${AWS::Region}.amazonaws.com
            Id: api-docs-s3
            S3OriginConfig:
              OriginAccessIdentity: !Join ['', ['origin-access-identity/cloudfront/', !Ref ApiDocsCloudFrontOai ]]
            OriginPath: !Sub "/${pBucketPath}"
        ViewerCertificate:
          AcmCertificateArn: !Ref pSslCertificate
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
      Tags:
        - Key: component
          Value: cdn

  ApiDocsCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties: 
      CachePolicyConfig: 
        Comment: !Sub CF Cache Policy for the API Docs ${pEnvironment}
        DefaultTTL: 300
        MaxTTL: 86400
        MinTTL: 1
        Name: !Sub
                - api-docs-cache-Policy-${ResourceName}
                - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]

        ParametersInCacheKeyAndForwardedToOrigin: 
          CookiesConfig: 
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig: 
            HeaderBehavior: none
          QueryStringsConfig: 
            QueryStringBehavior: whitelist
            QueryStrings: 
              - cb

  ApiDocsCloudFrontOai:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub CF Cache Policy for the API Docs ${pEnvironment}


Outputs:
  ApiDocsBucketName:
    Value: !Ref ApiDocsBucket
  ApiDocsBucketArn:
    Value: !GetAtt ApiDocsBucket.Arn
  ApiDocsCloudFrontDistributionId:
    Value: !Ref ApiDocsCloudFrontDistro