AWSTemplateFormatVersion: "2010-09-09"
Description: Code pipeline for API docs

Parameters:
  pEnvironment:
    Type: String
    Description: The AWS environment this belongs to
  pCloudFormationServiceRole:
    Type: String
    Description: Common service role used by Cloudformation
  pCodeBuildServiceRole:
    Type: String
    Description: Common service role used by CodeBuild
  pAppStackName:
    Type: String
    Description: The name of the application stack
  pCodePipelineServiceRole:
    Type: String
    Description: Common service role used by CodePipeline
  pArtifactsBucket:
    Type: String
    Description: Common artifacts bucket used by CodePipeline and CodeBuild
  pGitHubRepositoryName:
    Type: String
    Description: GitHub repository name.
  pGitHubOwner:
    Type: String
    NoEcho: true
  pGitHubBranch:
    Type: String
    Default: test/userdetails
  pCodestarConnection:
    Type: String

Resources:
 
  BuildTemplateConfig:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub api-docs-template-config-${pEnvironment}
      Description: Load the environment and build the CloudFormation template config file
      ServiceRole: !Ref pCodeBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:6.0
        EnvironmentVariables:
          - Name: "AWS_ARTIFACTS_BUCKET"
            Value: !Ref pArtifactsBucket
      Source:
        Type:  CODEPIPELINE
        BuildSpec: template-config-buildspec.yaml
      TimeoutInMinutes: 5

  Pipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Sub 1-apidocs-${pEnvironment}
      RoleArn: !Ref pCodePipelineServiceRole
      ArtifactStore:
        Type: S3
        Location: !Ref pArtifactsBucket
      Stages:
      - Name: Source
        Actions:
          - Name: CheckoutSrc
            ActionTypeId:
              Category: Source
              Owner: AWS
              Provider: CodeStarSourceConnection
              Version: 1
            Configuration:
              ConnectionArn: !Ref pCodestarConnection
              FullRepositoryId: !Sub ${pGitHubOwner}/${pGitHubRepositoryName}
              BranchName: !Ref pGitHubBranch
              OutputArtifactFormat: CODE_ZIP
              DetectChanges: false
            Namespace: CheckoutSrcNS
            OutputArtifacts:
              - Name: 'ApiDocsSourceArtifact'
      - Name: Deploy
        Actions:
          - Name: BuildTemplateConfig
            ActionTypeId:
              Owner: AWS
              Category: Build
              Version: 1
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref BuildTemplateConfig
              EnvironmentVariables: '[
                                       { "name":"SRC_BRANCH", "value":"#{CheckoutSrcNS.BranchName}" },
                                       { "name":"COMMIT_ID", "value":"#{CheckoutSrcNS.CommitId}" }
                                     ]'
            Namespace: BuildTemplateConfigNS
            InputArtifacts:
              - Name: 'ApiDocsSourceArtifact'
            OutputArtifacts:
              - Name: BuildTemplateConfigArtifact
            RunOrder: 1
          - Name: DeployCFStack
            ActionTypeId:
              Owner: AWS
              Category: Deploy
              Version: 1
              Provider: CloudFormation
            Configuration:
              TemplatePath: 'BuildTemplateConfigArtifact::cicd/api_docs.yaml'
              TemplateConfiguration: 'BuildTemplateConfigArtifact::cicd/template_config.json'
              ActionMode: REPLACE_ON_FAILURE
              Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
              RoleArn: !Ref pCloudFormationServiceRole
              StackName: !Ref pAppStackName
            InputArtifacts:
              - Name: 'BuildTemplateConfigArtifact'
            Namespace: CloudFormationOutNS
            OutputArtifacts: []
            RunOrder: 2         

Outputs:
  PipelineUrl:
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${Pipeline}
