version: 0.2

env:
  shell: bash
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  exported-variables:
    - CODEBUILD_BUILD_NUMBER

phases:

  install:
    runtime-versions:
      python: 3.10
    commands:
      - #echo setting up build environment
      - echo Running on $(lsb_release -d | cut -f2)
      - echo aws-cli version $(aws --version)
    finally:
      - #echo This always runs even if the update or install command fails
      - #notify Slack on failure


  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo source branch is $BRANCH
      - environment=$(cicd/branch_2_env.py --branch $BRANCH)
      - echo Environment is $environment
      - echo loading config..
      - source userdetails/config
    finally:
      - #echo This always runs
      - #notify Slack on failure

  build:
    commands:
      - echo Entered the build phase...
      - echo Exporting openAPI spec
      - if [ "$REST_API" == "true" ] ; then
           aws apigateway get-export 
             --rest-api-id $REST_API_ID
             --export-type oas30
             --stage-name $REST_STAGE_NAME
             $REST_OPENAPI_EXPORT_FILENAME ;
        fi
      - if [ "$HTTP_API" == "true" ] ; then
           aws apigatewayv2 export-api
             --api-id $HTTP_API_ID
             --output-type JSON
             --specification OAS30
             --stage-name $HTTP_DEV_STAGE_NAME
             $HTTP_OPENAPI_EXPORT_FILENAME ;
        fi
    finally:
      - #echo This always runs
      - #notify Slack on failure


  post_build:
    commands:
      - #echo Entered the post_build phase...
      - #notify Slack

artifacts:
  files:
    - $REST_OPENAPI_EXPORT_FILENAME
    - $HTTP_OPENAPI_EXPORT_FILENAME
  name: export-openapi
  discard-paths: yes
