version: 0.2
###
# Deletes all objects from the documentation bucket, this needs to be done 
# so the bucket can be removed during teardown

env:
  shell: bash

phases:
  build:
    commands:
      - echo s3 rm s3://$DOCUMENTATION_BUCKET --recursive
      - aws s3 rm s3://$DOCUMENTATION_BUCKET --recursive 